name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    if: github.ref == 'refs/head/main' #https://stackoverflow.com/questions/71535871/trigger-github-action-only-when-new-tags-on-master-branch
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - uses: ncipollo/release-action@v1
      name: Create Release
      with:
        body: # date
        generateReleaseNotes: true
        makeLatest: true
        omitName: true
